version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          name: run textlint
          command: |
            yarn textlint README.md
      - run:
          name: run reviewdog
          when: on_fail
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
            yarn textlint -f checkstyle README.md | ./bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-check"
      - save_cache:
          key: v1-dependency-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  main:
    jobs:
      - lint
